fix: #2 update activities
xiyou-linuxer/XiyouLinuxWebsite2024 pull request #5
Opened 2024-04-01 14:21 UTC by JINGzmr

2024-04-01 15:43 UTC, L33Z22L11 requested changes

2024-04-01 15:43 UTC, L33Z22L11 commented on docs/event/index.md
> +
为了维护文档的规范性，请遵循以下规则：

- 标题应当上下空行
- 不要出现多余的空行

2024-04-01 16:03 UTC, JINGzmr commented on docs/event/index.md
> +
收到

2024-04-02 11:37 UTC, L33Z22L11 approved these changes
LGTM

2024-04-02 11:37 UTC, merged